excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://aragostinho.github.io
title: "André Agostinho"
email: andre@magnadev.com.br
author: André Rocha Agostinho
description: Programing,  Agile Methodology e Devops  
paginate: 3
google_analytics: 
