excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://aragostinho.github.io
title: "André Rocha Agostinho - Software Engineer"
email: andre@magnadev.com.br
author: André Rocha Agostinho
description: Programing,  Agile Methodology e Devops  
paginate: 3
google_analytics: 
